			<footer id="footer">
				<div id="footer-inner" class="background-grey">
					<div class="right-block">
						<a href="<s:text name="webportal.footer.companyurl"/>" class="copyright text-grey">
							<s:text name="webportal.footer.companylinktxt"/>
						</a>
						<a href="#" class="copyright text-grey">
							&#169 &#32<s:text name="webportal.footer.copyright"/>
						</a>
					</div>
				</div>
			</footer>